"""in the table user added fields amount_of_days, begin_of_the_day, end_of_the_day

Revision ID: 4a8365b612e2
Revises: a475617ffeb7
Create Date: 2023-02-23 12:36:18.327089

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a8365b612e2'
down_revision = 'a475617ffeb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('amount_of_days', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('begin_of_the_day', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('end_of_the_day', sa.Time(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('end_of_the_day')
        batch_op.drop_column('begin_of_the_day')
        batch_op.drop_column('amount_of_days')

    # ### end Alembic commands ###
